version: '3'
services:
  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    networks:
    - node-network
    depends_on:
      - nodejs
      - mysql

  nodejs:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: nodejs_app
    entrypoint: dockerize -wait tcp://mysql:3306 -timeout 10s docker-entrypoint.sh node index.js
    restart: always
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - node-network
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    container_name: mysql_db
    environment:
      - MYSQL_DATABASE=fullcycle
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - node-network

networks:
  node-network:
    driver: bridge